listing = dir('D:/waveforms/maximuses_all/*_old.txt');
listing = {listing.name};

data = [];
for folder = 1:length(listing)
    file = fullfile('D:/waveforms/maximuses_all/', listing{folder});  
    input = fopen(file,'r');
    formatSpec = '%f %f\n';
    currentIter = fscanf(input, formatSpec,[2 Inf]);
    avg = mean(currentIter(2,:));
    data = [data [currentIter(1,1) avg]'];
    fclose(input);
end;

%CREATEFIT(X_O,Y_O)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x_o
%      Y Output: y_o
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jan-2017 01:02:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x_o, y_o );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
h = plot( fitresult, xData, yData );
% Label axes
xlabel x_o
ylabel y_o
grid on
hold on
%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x_old, y_old );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
plot( fitresult,'--', xData, yData );
% Label axes
xlabel x_o
ylabel y_o
grid on